language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t gsaltd/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run gsaltd/react-test npm test -- --coverage

after_success:
    - docker build -t gsaltd/nulti-client ./client
    - docker build -t gsaltd/nulti-nginx ./nginx
    - docker build -t gsaltd/nulti-server ./server
    - docker build -t gsaltd/nulti-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -username "$DOCKER_ID" --password-stdin
    - docker push gsaltd/nulti-client
    - docker push gsaltd/nulti-nginx
    - docker push gsaltd/nulti-server
    - docker push gsaltd/nulti-worker
