language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t gsaltd/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run gsaltd/react-test npm test -- --coverage

after_success:
    - docker build -t gsaltd/multi-client ./client
    - docker build -t gsaltd/multi-nginx ./nginx
    - docker build -t gsaltd/multi-server ./server
    - docker build -t gsaltd/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push gsaltd/multi-client
    - docker push gsaltd/multi-nginx
    - docker push gsaltd/multi-server
    - docker push gsaltd/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-944354727820"
    bucket_path: "multi-docker"
    on: 
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    